spring:
  h2:
    console:
      enabled: true
      path: "/h2"
  datasource:
    url: "jdbc:h2:file:./state"
    username: "sa"
    password:
    driver-class-name: "org.h2.Driver"
  jpa:
    hibernate:
      ddl-auto: update
bolts:
  embedded-kafka:
    enabled: true
    zookeper-port: 2181
    kafka-port: 9092
  kafka:
    "[bootstrap.servers]":      "localhost:9092"
    "[delete.enable.topic]":    "true"
    #kafkaConsumer
    "[group.id]":               "default-group"
    "[heartbeat.interval.ms]":  "59990"
    "[session.timeout.ms]":     "60000"
    "[enable.auto.commit]":     "true"
    "[key.deserializer]":       "org.apache.kafka.common.serialization.LongDeserializer"
    "[value.deserializer]":     "org.apache.kafka.common.serialization.StringDeserializer"
    # producer
    "[clinet.id]":              "default-client"
    "[key.serializer]":         "org.apache.kafka.common.serialization.LongSerializer"
    "[value.serializer]":       "org.apache.kafka.common.serialization.StringSerializer"
logging:
  level:
    root: INFO
    kic: DEBUG
    org:
      apache:
        kafka:
          clients:
            NetworkClient: ERROR

