spring:
  devtools:
    restart:
      enabled: false
  h2:
    console:
      enabled: true
      path: "/h2"
  datasource:
    #url: "jdbc:h2:file:./state"
    url: "jdbc:h2:mem:state"
    username: "sa"
    password:
    driver-class-name: "org.h2.Driver"
  jpa:
    hibernate:
      ddl-auto: update
bolts:
  embedded-kafka:
    enabled: true
    zookeper-port: 2181
    kafka-port: 9092
  kafka:
    #kafak simple client
    "[max.connection.retry]":   "100"
    #kafka client
    "[bootstrap.servers]":      "localhost:9092"
    "[delete.enable.topic]":    "true"
    #kafkaConsumer
    "[group.id]":               "default-group"
    "[auto.offset.reset]":      "earliest"
    "[heartbeat.interval.ms]":  "59990"
    "[fetch.max.wait.ms]":      "5000"
    "[session.timeout.ms]":     "60000"
    "[enable.auto.commit]":     "true"
    "[key.deserializer.java.lang.Long]":     "org.apache.kafka.common.serialization.LongDeserializer"
    "[value.deserializer.java.lang.String]": "org.apache.kafka.common.serialization.StringDeserializer"

    # producer
    "[client.id]":              "default-client"
    "[key.serializer.java.lang.Long]":     "org.apache.kafka.common.serialization.LongSerializer"
    "[value.serializer.java.lang.String]": "org.apache.kafka.common.serialization.StringSerializer"

logging:
  level:
    root: INFO
    kic: DEBUG
    org:
      apache:
        kafka:
          clients:
            NetworkClient: ERROR

